# This is a basic workflow to help you get started with Actions

name: Preview diff

# Controls when the workflow will run
on:
  issue_comment:
    types:
    - created
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  preview:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/diff'}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: git log -1

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          git checkout hello
          git diff main hello > ${{ github.workspace }}/diff.txt
          
      - uses: actions/upload-artifact@v3
        with:
          name: prod-diff
          path: ${{ github.workspace }}/diff.txt        
      - id: comment
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: ${{ github.workspace }}/diff.txt 
          check_for_duplicate_msg: false          
